WebBooks/WebBooks/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

WebBooks/catalog/urls.py
from django.urls import path

from .import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('logout', views.logout, name='logout'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('edit_authors/', views.edit_authors, name='edit_authors'),
    path('authors_add/', views.add_author, name='authors_add'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('edit_author/<int:id>/', views.edit_author, name='edit_author'),
    path('edit_books/', views.edit_books, name='edit_books'),
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/update/<int:pk>/', views.BookUpdate.as_view(), name='book_update'),
    path('book/delete/<int:pk>', views.BookDelete.as_view(), name='book_delete'),


]

WebBooks/catalog/models.py
from datetime import date

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text=" Введите жанр",
                            verbose_name=" Жанр книги")

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=20,
                            help_text=" Введите язык книги",
                            verbose_name="Язык книги")

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField(max_length=20,
                            help_text=" Введите наименование издетельства",
                            verbose_name=" Издательство")

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100,
                                  help_text="Введите имя",
                                  verbose_name="Имя автора")
    last_name = models.CharField(max_length=100,
                                  help_text="Введите фамилию",
                                  verbose_name="Фамилия автора")
    date_of_birth = models.DateField(help_text="Введите дату рождения",
                                     verbose_name="Дата рождения",
                                     null=True, blank=True)
    about = models.TextField(help_text="Введите сведения об авторе",
                             verbose_name="Сведения об авторе")
    photo = models.ImageField(upload_to='images',
                              help_text="Введите фото автора",
                              verbose_name="Фото автора",
                              null=True, blank=True)

    def __str__(self):
        return self.last_name


class Book(models.Model):
    title = models.CharField(max_length=200,
                                  help_text="Введите название книги",
                                  verbose_name="Название книги")
    genre = models.ForeignKey('Genre',
                              on_delete=models.CASCADE,
                              help_text="Выберите жанр для книги",
                              verbose_name="Жанр книги", null=True)
    language = models.ForeignKey('Language',
                                 on_delete=models.CASCADE,
                                 help_text="Выберите язык книги",
                                 verbose_name="Язык книги", null=True)
    publisher = models.ForeignKey('Publisher',
                                  on_delete=models.CASCADE,
                                  help_text="Выберите издательство",
                                  verbose_name="Издательство", null=True)
    year = models.CharField(max_length=4,
                            help_text="Введите год издания",
                            verbose_name="Год издания")
    author = models.ManyToManyField('Author',
                                    help_text="Выберите автора (авторов) книги",
                                    verbose_name="Авторы (авторы) книги")
    summary = models.TextField(max_length=1000,
                               help_text="Введите краткое описание книги",
                               verbose_name="Аннотация книги")
    isbn = models.CharField(max_length=13,
                            help_text="Должно содержать 13 символов",
                            verbose_name="ISBN книги")
    price = models.DecimalField(decimal_places=2, max_digits=7,
                                help_text="Введите цену книги",
                                verbose_name="Цена (руб.)")
    photo = models.ImageField(upload_to='images',
                              help_text="Введите изображение обложки",
                              verbose_name="Изображение обложки")

    def display_author(self):
        return ', '.join([author.last_name for author in
                          self.author.all()])
    display_author.short_description = "Авторы"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])


class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введите статус экземпляра книги",
                            verbose_name="Статус экземпляра книги")

    def __str__(self):
        return self.name



class BookInstance(models.Model):
    book = models.ForeignKey('Book',
                             on_delete=models.CASCADE, null=True)
    inv_nom = models.CharField(max_length=20,
                               null=True,
                               help_text="Введите инвентарный номер экземпляра",
                               verbose_name="Инвентарный номер")
    status = models.ForeignKey('Status',
                               on_delete=models.CASCADE,
                               null=True,
                               help_text='Изменить состояние экземпляра',
                               verbose_name="Статус экземпляра книги")
    due_back = models.DateField(null=True,
                                blank=True,
                                help_text="Введите конец срока статуса",
                                verbose_name="Дата окончания статуса")
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL,
                                 null=True, blank=True,
                                 verbose_name="Заказчик",
                                 help_text="Выберите книги заказчика")

    objects = models.Manager
    class Meta:
        ordering = ["due_back"]
    def __str__(self):
        return '%s %s %s' % (self.inv_nom, self.book, self.status)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False




# Create your models here.

WebBooks/catalog/forms.py
from django import forms
from datetime import date

from .models import Book


class Form_add_author(forms.Form):
    first_name = forms.CharField(label="Имя автора")
    last_name = forms.CharField(label="Фамилия автора")
    date_of_birth = forms.DateField(label="Дата рождения",
                                    initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    about = forms.CharField(label="Сведения об авторе",
                            widget=forms.Textarea)
    photo = forms.ImageField(label="Фото автора")

class BookModelForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

WebBooks/catalog/views.py
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from django import forms
from .forms import Form_add_author
from .models import Book, BookInstance, Author


def index (request):
    text_head = 'На нашем сайте вы можете получить книги в электронном виде'
    books = Book.objects.all()
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(
        status__exact=2).count()
    authors = Author.objects
    num_authors = Author.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {'text_head': text_head,
               'books': books, 'num_books': num_books,
               'num_instances': num_instances,
               'num_instances_available': num_instances_available,
               'authors': authors, 'num_authors': num_authors,
               'num_visits': num_visits}
    return render(request, 'catalog/index.html', context)

class BookListView(ListView):
    model = Book
    context_object_name = 'books'
    paginate_by = 3

class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'

class AuthorListView(ListView):
    model = Author
    paginate_by = 4

class AuthorDetailView(DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    def get_queryset(self):
        return BookInstance.objects.filter(
            borrower=self.request.user).filter(
            status__exact='2').order_by('due_back')


class Form_edit_author(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('edit_books')

class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('edit_books')

class BookDelete(DeleteView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('edit_books')
def about(request):
    text_head = 'Сведения о компании'
    name = 'ООО Интеллектуальные информационные системы'
    rab1 = ('Разработка приложений на основе'
            'систем искусственного интеллека')
    rab2 = 'Распознавание объектов дорожной инфраструктуры'
    rab3 = ('Создание графических АРТ-объектов на основе'
            'систем искусственного интеллекта')
    rab4 = ('Создание цифровых интерактивных книг, учебныых пособий,'
            'автоматизированных обучающих систем')
    context = {'text_head': text_head, 'name': name,
               'rab1': rab1, 'rab2': rab2,
               'rab3': rab3, 'rab4': rab4}
    return render(request, 'catalog/about.html', context)

def contact(request):
    text_head = 'Контакты'
    name = 'ООО Интеллектуальные информационные системы'
    address = 'Москва, ул. Планерная, д. 20, к. 1'
    tel = '495-345-45-45'
    email = 'DoBook_Co@mail.ru'
    context = {'text_head': text_head, 'name': name,
               'address': address, 'tel': tel,
               'email': email}
    return render(request, 'catalog/about.html', context)

def edit_authors(request):
    author = Author.objects.all()
    context = {'author': author}
    return render(request, "catalog/edit_authors.html", context)

def edit_author(request, id):
    author = Author.objects.get(id=id)
    if request.method == "POST":
        instance = Author.objects.get(pk=id)
        form = Form_edit_author(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/edit_authors/")
    else:
        form = Form_edit_author(instance=author)
        content = {"form": form}
        return render(request, "catalog/edit_author.html", content)

def add_author(request):
    if request.method == 'POST':
        form = Form_add_author(request.POST, request.FILES)
        if form.is_valid():
            first_name = form.cleaned_data.get("first_name")
            last_name = form.cleaned_data.get("last_name")
            date_of_birth = form.cleaned_data.get("date_of_birth")
            about = form.cleaned_data.get("about")
            photo = form.cleaned_data.get("photo")
            obj = Author.objects.create(
                first_name=first_name,
                last_name=last_name,
                date_of_birth=date_of_birth,
                about=about,
                photo=photo
            )
            obj.save()
            return HttpResponseRedirect(reverse('authors-list'))
    else:
        form = Form_add_author()
        context = {"form": form}
        return render(request, "catalog/authors_add.html", context)

def delete(request, id):
    try:
        author = Author.objects.get(id=id)
        author.delete()
        return HttpResponseRedirect("/edit_authors/")
    except:
        return HttpResponseNotFound("<h2>Автор не найден</h2>")

def edit_books(request):
    book = Book.objects.all()
    context = {'book': book}
    return render(request, "catalog/edit_books.html", context)
# Create your views here.

WebBooks/templates/catalog/author_detail.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="container text-start">
    <div class="row my-2">
        <h4>{{ object.first_name }} {{ author.last_name }}</h4>
        <p>Родился - {{ author.date_of_birth }}</p>
        <p>Фото (портрет)</p>
        <p><img src="{{ author.photo.url }}"
            alt="connect" style="max-height:200px"></p>
        <div class="row my-2">
            <div class="col my-2">
                <a href="{{ author.photo.url }}" class="btn btn-primary"
                   target="_blank">Показать</a>
            </div>
        </div>
        <div class="row my-2">{{author.about}}</div>
    </div>
</div>
{% endblock content%}

WebBooks/templates/catalog/author_list.html
{% extends "catalog/base.html" %}
{% block content %}
    <h4>Список авторов книг</h4>
    {% if author_list %}
        <table class="table table-striped table-bordered text-start">
            <thead>
                <tr>
                    <th>Автор</th>
                    <th>Фото</th>
                    <th>Показать фото</th>
                </tr>
            </thead>
            <tbody>
            {% for author in author_list.all %}
            <tr>
                <td><a href="{{ author.id }}"> {{ author.first_name }}
                    {{ author.last_name }}</a></td>
                <td><img src="{{ author.photo.url }}" alt="connect"
                    style="max-height:100px"></td>
                <td><a href="{{ author.photo.url }}"
                    class="btn btn-primary"
                    target="_blank">Показать</a></td>
            </tr>
            {% endfor%}
            </tbody>
        </table>
    {% else %}
        <p>В базе данных нет авторов</p>
    {% endif %}
{% endblock content %}

WebBooks/templates/catalog/authors_add.html
{% extends "catalog/base.html" %}
{% block content %}
<h5>Добавить в БД автора книги</h5>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <table class="table text-start">
                {{ form }}
            </table>
        </div>
        <div class="col-2"></div>
    </div>
    <input type="submit" value="Сохранить">
</form>
{% endblock content %}

WebBooks/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" >
    <script defer src="/static/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="container-fluid p-1 bg-primary text-white text-center">
        <div class="row">
            <div class="col-2 text-start">
                <img src="{% static 'images/Company_Logo.jpg' %}" width="70"
                     height="70">
            </div>
            <div class="col-10">
                <h1>Мир книг - печатные и электронные интерактивные книги</h1>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row bg-warning text-center">
            <h6>
                <a href="{% url 'index' %}">Главная страница</a>
                <a href="{% url 'about' %}">О компании</a>
                <a href="{% url 'contact' %}">Контакты</a>
            </h6>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row text-center text-primary fs-1 fw-bold">
            <div>{% block header %}
                {% endblock header %}
            </div>
        </div>
        <div class="row text-center text-body">
            <div class="col-2">
                {% block sidebar %}
                <nav class="nav flex-column">
                    <a class="nav-link" href="{% url 'books' %}">Все книги</a>
                    <a class="nav-link" href="{% url 'authors' %}">Все авторы</a>
                    {% if user.is_authenticated %}
                        <a class="nav-link"
                           href="{% url 'logout' %}"?next="{{request.path}}">Выход</a>
                        <div>Вошёл: {{ user.get_username }}</div>
                        <a class="nav-link"
                           href="{% url 'edit_authors' %}">Редактор авторов</a>
                        <a class="nav-link"
                           href="{% url 'edit_books' %}">Редактор книг</a>
                        <a class="nav-link"
                           href="{% url 'my-borrowed' %}">Мои заказы</a>
                    {% else %}
                        <a class="nav-link"
                           href="{% url 'login' %}"?next="{{request.path}}">Вход</a>
                    {% endif%}
                </nav>
                {% endblock sidebar %}
            </div>
            <div class="col-10">
                <div class="row text-center">
                    {% block content %}
                    {% endblock content %}

                    <!--PAGINATOR-->
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.paginator.num_pages > 1 %}
                                {% if page_obj.has_previous %}
                                    <a href="?page=1">&laquo; Первая</a>
                                    <a href="?page={{ page_obj.previous_page_number }}">
                                        Предыдущая</a>
                                {% endif %}

                            <span class="current">
                                Стр. {{ page_obj.number }}
                                    из {{ page_obj.paginator.num_pages }}.
                            </span>

                                {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}">
                                        Следующая</a>
                                    <a href="?page={{ page_obj.paginator.num_pages }}">
                                        Предыдущая &raquo;</a>
                                {% endif %}
                            {% endif %}
                        </span>
                    </div>
                    <!--PAGINATOR-->
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row bg-primaty text-center text-white 1h-1 my-2">
            {% block footer%}
                <p>Copyright ООО "Интеллектуальные информационные системы", 2024.
                    Все права защищены</p>
            {% endblock footer%}
        </div>
    </div>
</body>
</html>

WebBooks/templates/catalog/book_confirm_delete.html
{% extends "catalog/base.html" %}
{% block content %}
<h1>Удаление книги</h1>
<p>Вы уверены, что хотите удалить книгу: {{ book }}?</p>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="submit" action="" value="Да, удалить" />
</form>
{% endblock content %}

WebBooks/templates/catalog/book_detail.html
{% extends "catalog/base.html" %}
{% block content %}
    <div class="container text-start">
        <div class="row my-2">
            <h1>Название книги - "{{ book.title }}"</h1>
        </div>
        <div class="row my-2">
            <p><strong>Автор:</strong>
                {% for author in book.author.all %}
                    <a href="/authors/{{ author.id }}">
                        {{ author.first_name }} {{ author.last_name }}</a>
                {% endfor %}
            </p>
        </div>
        <img src="{{ book.photo.url }}" alt="connect"
                style="max-height:200px">
        <a href="{{ book.photo.url }}" class="btn btn-primary"
            target="_blank">Показать</a>
        <div class="row my-2">
            <div class="col">
                <p><strong>Цена:</strong> {{ book.price }}</p>
            </div>
        </div>
        <div class="row my-2">
            <div class="col">
                <p><strong>Аннотация:</strong> {{ book.summary }}</p>
            </div>
        </div>
        <div class="row my-2">
            <div class="col mx-2 bg-primary text-white">
                <p><strong>Жанр:</strong> {{ book.genre }}</p>
            </div>
            <div class="col mx-2 bg-primary text-white">
                <p><strong>ISBN:</strong> {{ book.isbn }}</p>
            </div>
            <div class="col mx-2 bg-primary text-white">
                <p><strong>Язык:</strong> {{ book.language }}</p>
            </div>
            <div class="col mx-2 bg-primary text-white">
                <p><strong>Издательство:</strong> {{ book.publisher }}</p>
            </div>
        </div>
        <div style="margin-left:20px; margin-top:10px">
            <h4>Количетсво экземпляров книг в БД</h4>
            {% for copy in book.bookinstance_set.all %}
                <hr>
                    <p class="text-muted">
                        <strong>Инвентарный номер:</strong> {{ copy.id }}
                    </p>
                    <p class="text-success">
                        <strong>Статус экземпляра книги:</strong> {{ copy.status }}
                    </p>
            {% endfor %}
        </div>
    </div>
{% endblock content%}

WebBooks/templates/catalog/book_form.html
{% extends "catalog/base.html" %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="text-start">
        {{ form.as_table }}
    </table>
    <input type="submit" value="Сохранить" />
</form>
{% endblock content %}

WebBooks/templates/catalog/book_list.html
{% extends "catalog/base.html" %}
{% block content %}
    <div class="row text-center text-dark 1h-2">
        <h4>Список книг в БД</h4>
    </div>
    {% if books %}
        <table class="table table-striped table-bordered text-start">
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Автор</th>
                    <th>Жанр</th>
                    <th>Обложка</th>
                    <th>Показать обложку</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                    <tr>
                        <td><a href="{{ book.id }}">{{ book.title }} </a></td>
                        <td>{{ book.display_author }}</td>
                        <td>{{ book.genre }}</td>
                        <td><img src="{{ book.photo.url }}" alt="connect"
                            style="max-height:100px"></td>
                        <td><a href="{{ book.photo.url }}"
                            class="btn btn-primary"
                            target="_blank">Показать</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>В базе данных нет книг</p>
    {% endif %}
{% endblock content %}

WebBooks/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "catalog/base.html" %}
{% block content %}
    <h1>Взятые книги</h1>
    {% if bookinstance_list %}
        {% for bookinst in bookinstance_list %}
            <div class="{% if bookinst.is_overdue %} text-danger{% endif %}">
                <a href="{% url 'book-detail' bookinst.book.pk %}">
                    {{bookinst.book.title}}</a>
                    {{bookinst.due_back}}
            </div>
        {% endfor %}
    {% else %}
        <p>Нет книг со статусом В ЗАКАЗЕ</p>
    {% endif %}
{% endblock content %}

WebBooks/templates/catalog/contact.html
{% extends "catalog/base.html" %}
<head>
    {% load static %}
</head>
{% block content %}
<div class="container-fluid">
    <div class="row my-2 text-center">
        <div class="col-5"></div>
        <div class="col-1 text-center">
            <img src="{% static 'images/small_logo.jpg' %}">
        </div>
        <div class="col-5"></div>
    </div>
    <div class="row my-2 text-primary text-center">
        <h3>{{ name }}</h3>
    </div>
    <div class="row my-2 text-muted">
        <h4 class="text-center">{{ text_head }}</h4>
    </div>
    <div class="row my-2">
        <div class="col-3"></div>
        <div class="col-6">
            <table class="table table-striped table-bordered text-start">
                <thead>
                    <tr>
                        <th>Адрес</th>
                        <th>Телефон</th>
                        <th>e-mail</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ address }}</td>
                        <td>{{ tel }}</td>
                        <td>{{ email }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-3"></div>
        <div class="row my-2 text-center">
            <div class="col-2"></div>
            <div class="col-8">
                <img src="{% static 'images/address.jpg' %}" class="img-fluid">
            </div>
            <div class="col-2"></div>
        </div>
    </div>
</div>
{% block content%}

WebBooks/templates/catalog/edit_author.html
{% extends "catalog/base.html" %}
{% block content %}
    <div class="row text-start 1h-2">
        <h3>Изменить сведения об авторе</h3>
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="text-start">
            {% for field in form %}
                <tr>
                    <th>{{ field.label_tag }}
                        {{ field.errors }}
                    </th>
                    <th>{{ field }}</th>
                </tr>
            {% endfor %}
            <th>
                <button type="submit">Сохранить</button>
            </th>
        </table>
    </form>
{% endblock content %}

WebBooks/templates/catalog/edit_authors.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="row text-start 1h-2">
    <h5>Список авторов для редактирования</h5>
</div>
<div class="row">
    <div class="col-2"></div>
    <a href="/authors_add/{{authors_add}}">Добавить автора</a>
    <div class="col-8">
        <table class="table table-striped table-bordered text-start">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Редактировать</th>
                </tr>
            </thead>
            <tbody>
                {% if author %}
                    {% for author in author.all %}
                        <tr>
                            <td>{{author.id}}</td>
                            <td>{{author.first_name}}</td>
                            <td>{{author.last_name}}</td>
                            <td><a href="/edit_author/{{author.id}}">Изменить</a>,
                                <a href="/delete/{{author.id}}">Удалить</a></td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <p>В базе данных нет авторов</p>
                {% endif %}
            </tbody>
        </table>
    </div>
    <div class="col-2"></div>
</div>
{% endblock content %}

WebBooks/templates/catalog/edit_books.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="row text-start 1h-2">
    <h5>Список книг для редактирования</h5>
</div>
<div class="row">
    <div class="col-2"></div>
    <a href="{% url 'book_create' %}">Добавить книгу</a>
    <div class="col-8">
        <table class="table table-striped table-bordered text-start">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Название книги</th>
                    <th>Редактировать</th>
                </tr>
            </thead>
            <tbody>
                {% if book %}
                    {% for book in book.all %}
                        <tr>
                            <td>{{book.id}}</td>
                            <td>{{book.title}}</td>
                            <td><a href="/book/update/{{book.id}}">Изменить</a>,
                                <a href="/book/delete/{{book.id}}">Удалить</a></td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <p>В базе данных нет книг</p>
                {% endif %}
            </tbody>
        </table>
    </div>
    <div class="col-2"></div>
</div>
{% endblock content %}